### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by Torch567** [Uliony/CTSDG#2]
您好，，我在运行您的代码的时候遇到这样的问题，想让您帮忙解决一下。
D:\anaconda3\envs\pytorch\python.exe "D:\mycoding\code to try\CTSDG-master\train.py" 
Traceback (most recent call last):
  File "D:\mycoding\code to try\CTSDG-master\train.py", line 122, in <module>
    set_default()
  File "D:\mycoding\code to try\CTSDG-master\train.py", line 31, in set_default
    context.set_context(mode=context.GRAPH_MODE, device_target=config.device_target)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\mindspore\_checkparam.py", line 1234, in wrapper
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\mindspore\_checkparam.py", line 1203, in wrapper
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\mindspore\context.py", line 924, in set_context
    raise ValueError(f"For 'context.set_context', package type {__package_name__} support 'device_target' "
ValueError: For 'context.set_context', package type mindspore support 'device_target' type cpu, but got Ascend.

**Comment by Uliony** [comment]
你好，这段代码是适配华为昇腾设备的，如果你想在非昇腾设备上运行就需要将[default_config.yaml](https://github.com/Uliony/CTSDG/blob/master/default_config.yaml)中的device_target: Ascend改为CPU或者GPU
